# Generated by Django 2.0.1 on 2018-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_user', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='address',
            name='yzbm',
            field=models.CharField(default='', max_length=8),
        ),
    ]
