# Generated by Django 2.0.1 on 2018-02-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_user', '0003_auto_20180127_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mrdz',
            field=models.BooleanField(default=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='address',
            name='scbz',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
